name: Deno Outdated Action
description: "Automatically update Deno dependencies"
author: "William Horning"

branding:
  icon: "refresh-cw"
  color: "blue"

inputs:
  deno_version:
    description: "Deno version to use"
    required: false
    default: "2.x"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno_version }}
    - name: Update Packages
      shell: bash
      run: |
        deno run --allow-run=deno,git,gh --allow-read=.,$GITHUB_STEP_SUMMARY
          --allow-write=.,$GITHUB_STEP_SUMMARY --allow-env=GITHUB_STEP_SUMMARY,GH_TOKEN,NO_COLOR
          --allow-net scripts/update_deps.ts
      env:
        GH_TOKEN: ${{ github.token }}
